In [11]:
import pandas as pd
nd = pd.read_csv('/Users/zhangweiyuan/Desktop/dvfinal/disaster-bubblemap.csv')
nd

,Disaster Type,Country,ISO,Region,Continent,Location,Dis Mag Value,Dis Mag Scale,Latitude,Longitude,Total Deaths,Total Affected,Total Damages ('000 US$),CPI,Date
0,Flood,Afghanistan,AFG,Southern Asia,Asia,West,NaN,Km2,33.94,67.71,150,250000,0,16.157212,1972/1/15
1,Earthquake,Afghanistan,AFG,Southern Asia,Asia,Shamagan province (Hindu Kush),6.0,Richter,33.94,67.71,50,90000,0,21.988357,1976/3/19
2,Flood,Afghanistan,AFG,Southern Asia,Asia,"Herat, Farah, Kandahar",NaN,Km2,33.94,67.71,51,80000,0,21.988357,1976/4/15
3,Flood,Afghanistan,AFG,Southern Asia,Asia,"Central and Eastern regions, Pakistan border",NaN,Km2,33.94,67.71,120,271684,52000,25.204991,1978/7/15
4,Flood,Afghanistan,AFG,Southern Asia,Asia,Southern provinces,NaN,Km2,33.94,67.71,0,30000,0,31.841107,1980/3/15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10344,Storm,Zimbabwe,ZWE,Eastern Africa,Africa,"Mangwe, Bulilima, Guruve, Nkayi",NaN,Kph,-19.02,29.15,31,2000,0,92.734479,2016/12/9
10345,Storm,Zimbabwe,ZWE,Eastern Africa,Africa,"Chitungwiza (Harare), Makoni, Nyanga (Manicala...",NaN,Kph,-19.02,29.15,251,113023,189000,94.709841,2017/1/15
10346,Storm,Zimbabwe,ZWE,Eastern Africa,Africa,"Chikomba, Mudzi, Mutoko, UMP districts (Mash E...",NaN,Kph,-19.02,29.15,628,270186,0,98.781448,2019/3/14
10347,Flood,Zimbabwe,ZWE,Eastern Africa,Africa,"Masvingo, Mashonaland West",154678.0,Km2,-19.02,29.15,26,0,0,98.781448,2019/2/11
10348,Storm,Zimbabwe,ZWE,Eastern Africa,Africa,"Chivi, Masvingo Rural districts (Masvingo prov...",160.0,Kph,-19.02,29.15,3,2000,0,NaN,2021/1/23

In [12]:
nd_f = nd[nd['Disaster Type'] == 'Flood']
nd_f = nd_f.sort_values(by='Country')
nd_f

,Disaster Type,Country,ISO,Region,Continent,Location,Dis Mag Value,Dis Mag Scale,Latitude,Longitude,Total Deaths,Total Affected,Total Damages ('000 US$),CPI,Date
0,Flood,Afghanistan,AFG,Southern Asia,Asia,West,NaN,Km2,33.94,67.71,150,250000,0,16.157212,1972/1/15
103,Flood,Afghanistan,AFG,Southern Asia,Asia,"Kabul, Khost, Kunar, Paktya, Nangarrhar provinces",NaN,Km2,33.94,67.71,52,2597,0,90.010440,2013/8/1
102,Flood,Afghanistan,AFG,Southern Asia,Asia,"Baghlan, Ghor, Balkh provinces",14653.0,Km2,33.94,67.71,20,9500,0,90.010440,2013/4/25
100,Flood,Afghanistan,AFG,Southern Asia,Asia,"Sholey village (Yawan district, Badakhshan pro...",NaN,Km2,33.94,67.71,10,5000,0,90.010440,2013/2/4
99,Flood,Afghanistan,AFG,Southern Asia,Asia,"Keshendeh, Sholgareh districts (Balkh province...",NaN,Km2,33.94,67.71,20,5700,0,88.710969,2012/4/22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10332,Flood,Zimbabwe,ZWE,Eastern Africa,Africa,"Centenary, Guruve districts (Mashonaland Centr...",NaN,Km2,-19.02,29.15,13,30000,3600,68.415379,2001/2/15
10331,Flood,Zimbabwe,ZWE,Eastern Africa,Africa,"Chimanimani, Mutare districts (Manicaland prov...",295.0,Km2,-19.02,29.15,70,266000,72900,66.534994,2000/1/26
10342,Flood,Zimbabwe,ZWE,Eastern Africa,Africa,"Manicaland, Mashonaland Central, Mashonaland E...",NaN,Km2,-19.02,29.15,11,1500,0,91.470614,2014/12/15
10336,Flood,Zimbabwe,ZWE,Eastern Africa,Africa,Centenary district (Mashonaland Central province),13370.0,Km2,-19.02,29.15,3,15000,0,80.113393,2007/12/13
10347,Flood,Zimbabwe,ZWE,Eastern Africa,Africa,"Masvingo, Mashonaland West",154678.0,Km2,-19.02,29.15,26,0,0,98.781448,2019/2/11

In [13]:
nd_f1=nd_f.groupby(nd_f['Country'])['Total Affected'].sum()
nd_f1=nd_f1.tolist()
# nd_e1

nd_f2 = nd_f['Country'].unique()
nd_f2.sort()
nd_f2=nd_f2.tolist()
# nd_e2

nd_f3=nd_f['Latitude'].drop_duplicates().values.tolist()

nd_f4=nd_f['Longitude'].drop_duplicates().values.tolist()

In [14]:
nd_bubbleflood = pd.DataFrame([nd_f2, nd_f1, nd_f3, nd_f4])
nd_bubbleflood=nd_bubbleflood.T
nd_bubbleflood.columns = ['Country','Values','Latitude','Longitude']
nd_bubbleflood

            Country    Values Latitude Longitude
0       Afghanistan   1625771    33.94     67.71
1           Albania    205670    41.15     20.17
2           Algeria    497176    20.03      1.66
3    American Samoa         3    14.27    170.13
4            Angola   1295663    -11.2     17.87
..              ...       ...      ...       ...
182        Viet Nam  32967987    14.06    108.28
183           Yemen   1690227     15.1     43.88
184      Yugoslavia     12000     42.1     19.21
185          Zambia   5865680   -13.13     27.84
186        Zimbabwe    344022   -19.02     29.15

[187 rows x 4 columns]

In [15]:
from pyecharts.globals import GeoType
from pyecharts.globals import ChartType, SymbolType
from pyecharts.charts import Geo
from pyecharts import options as opts
from pyecharts.charts import Map

In [16]:
a1_listone=[]
datapairflood=[]
for i in range(0,len(nd_bubbleflood)):
    a1_listone=[nd_bubbleflood.iloc[i][0],nd_bubbleflood.iloc[i][1]]
    a=tuple(a1_listone)
    datapairflood.append(a)
#以上部分是为了产生元组列表，大家可以参考

worldmap1=Map(init_opts=opts.InitOpts(width="1200px",height="600px",bg_color='white'))
worldmap1.add(" ",data_pair=datapairflood,maptype="world",is_map_symbol_show=False)
worldmap1.set_series_opts(label_opts=opts.LabelOpts(is_show=True, font_size=5))
worldmap1.set_global_opts(
    title_opts=opts.TitleOpts(title="Total Affected People by Flood by Country"),
    legend_opts=opts.LegendOpts(is_show=False),
    visualmap_opts=opts.VisualMapOpts(min_=0,max_=20000000,orient="horizontal",type_ ="color",
                                                        #    range_color=['#FFFFFF','#E0FFFF','#AFEEEE','#ADD8E6','#87CEEB',
                                                        #    '#6495ED','#4682B4'],
                                                           pos_left=550,pos_bottom=60,item_width=15,item_height=200))
worldmap1.render()

'/Users/zhangweiyuan/Desktop/dvfinal/bubblemap_flood/render.html'

In [17]:
# datapairflood=[]
# for i in range(0,len(nd_bubbleflood)):
#     location=[nd_bubbleflood.iloc[i][2], nd_bubbleflood.iloc[i][3]]
#     datapairflood.append(location)#得到坐标数据列表

# datapairflood1=[]
# for i in range(0,len(nd_bubbleflood)):
#     value=[nd_bubbleflood.iloc[i][0], nd_bubbleflood.iloc[i][1]]
#     datapairflood1.append(value)#得到坐标数据列表

# # data = nd_bubble[['Country', 'Values']].values.tolist()

# df_flood = pd.read_csv(r'/Users/zhangweiyuan/Desktop/dvfinal/Sum_flood.csv', encoding='GBK')
# df_flood.columns = ['Country','Values']
# dataflood = df_flood[['Country', 'Values']].values.tolist()

# # data = [((i, datapair1[i][0]) for i in len(datapair1))]

# #构建元组列表成功
# geoflood = Geo(init_opts=opts.InitOpts(width="1200px",height="600px",bg_color='white'))
# geoflood.add_schema(maptype='world',itemstyle_opts=opts.ItemStyleOpts(color="white", border_color="#111")) #center代表这幅图的中心点，itemstyle_opts用于设置地图样式，这里设置了颜色

# for i in range(0,len(nd_bubbleflood)):
#     geoflood.add_coordinate(name=nd_bubbleflood.iloc[i][0],longitude=datapairflood[i][1],latitude=datapairflood[i][0])
# #添加新的坐标点，地理图geo与地图map的一个重要区别就是geo可以在地图上增设新的坐标点

# geoflood.add('',dataflood, type_=GeoType.SCATTER, symbol_size=10,color="#4682B4")

# # geo.add(data)


# geoflood.set_series_opts(label_opts=opts.LabelOpts(is_show=True,font_size=6,position="top",color='blue'))
# geoflood.set_global_opts(title_opts=opts.TitleOpts(title="Total Affected People by Earthquake by Country"))

# geoflood.render()